"""TSVECTOR filled

Revision ID: 1651e5d2c754
Revises: 40465cbf24ae
Create Date: 2024-11-09 13:06:58.467968

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1651e5d2c754'
down_revision = '40465cbf24ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_chunks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tsvector', postgresql.TSVECTOR(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_chunks', schema=None) as batch_op:
        batch_op.drop_column('tsvector')

    # ### end Alembic commands ###
