"""Create embedding

Revision ID: 984adde9a23a
Revises: 1651e5d2c754
Create Date: 2024-11-16 13:26:58.450731

"""
from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision = '984adde9a23a'
down_revision = '1651e5d2c754'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_chunks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=2048), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_chunks', schema=None) as batch_op:
        batch_op.drop_column('embedding')

    # ### end Alembic commands ###
