"""Add ContentItem model

Revision ID: e77f837d0bec
Revises: 984adde9a23a
Create Date: 2024-11-30 13:01:30.856285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e77f837d0bec'
down_revision = '984adde9a23a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_chunks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_item_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'content_items', ['content_item_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_chunks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('content_item_id')

    op.drop_table('content_items')
    # ### end Alembic commands ###
